name: CI

on:
  - push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-${{ runner.os }}-node-

      - run: npm install
      - run: npm run lint:ci
